import { StyleSheet } from "react-native";
import { Palette, Radius, Spacing, Typography } from "@/constants/design";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: Palette.background },
  centered: { flex: 1, alignItems: "center", justifyContent: "center" },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: Spacing.stackMd,
    paddingHorizontal: Spacing.containerMargin,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Palette.outlineVariant,
  },
  wordmark: {
    ...Typography.labelSm,
    color: Palette.onSurface,
    letterSpacing: 6,
    fontSize: 14,
  },
  editButton: {
    position: "absolute",
    right: Spacing.containerMargin,
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Palette.primary,
  },
  editButtonText: { ...Typography.labelSm, color: Palette.primary },
  editActions: {
    position: "absolute",
    right: Spacing.containerMargin,
    flexDirection: "row",
    gap: 8,
  },
  cancelButton: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Palette.outlineVariant,
  },
  cancelButtonText: { ...Typography.labelSm, color: Palette.onSurfaceVariant },
  saveButton: {
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: Radius.md,
    backgroundColor: Palette.primary,
  },
  saveButtonDisabled: { opacity: 0.6 },
  saveButtonText: { ...Typography.labelSm, color: Palette.onPrimary },
  scrollContent: {
    paddingHorizontal: Spacing.containerMargin,
    paddingTop: Spacing.stackLg,
    paddingBottom: Spacing.stackXl,
    gap: Spacing.stackLg,
  },
  profileHeader: { alignItems: "center", gap: Spacing.stackSm },
  avatar: {
    width: 96,
    height: 96,
    borderRadius: Radius.full,
    backgroundColor: Palette.surfaceContainerHigh,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: Spacing.stackSm,
  },
  avatarInitials: { ...Typography.headlineMd, color: Palette.onSurface },
  name: { ...Typography.headlineMd, color: Palette.onSurface },
  nameInput: {
    ...Typography.headlineMd,
    color: Palette.onSurface,
    borderBottomWidth: 1,
    borderBottomColor: Palette.primary,
    paddingVertical: 2,
    paddingHorizontal: 4,
    textAlign: "center",
    minWidth: 160,
  },
  email: { ...Typography.bodyMd, color: Palette.onSurfaceVariant },
  bentoGrid: { gap: Spacing.gutter },
  bentoRow: { flexDirection: "row", gap: Spacing.gutter },
  card: {
    backgroundColor: Palette.surfaceContainer,
    borderRadius: Radius.lg,
    padding: Spacing.stackLg,
  },
  cardHalf: { flex: 1 },
  cardLabel: {
    ...Typography.labelSm,
    color: Palette.onSurfaceVariant,
    marginBottom: Spacing.stackSm,
  },
  cardValue: { ...Typography.titleLg, color: Palette.onSurface },
  fieldInput: {
    ...Typography.titleLg,
    color: Palette.onSurface,
    borderBottomWidth: 1,
    borderBottomColor: Palette.primary,
    paddingVertical: 2,
    minWidth: 40,
  },
  heightRow: { flexDirection: "row", alignItems: "center", gap: 2 },
  heightInput: { minWidth: 28, textAlign: "center" },
  heightSep: { ...Typography.titleLg, color: Palette.onSurface },
  section: { gap: Spacing.stackMd },
  sectionTitle: {
    ...Typography.headlineMd,
    color: Palette.onSurface,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Palette.surfaceVariant,
    paddingBottom: Spacing.stackSm,
  },
  prefRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: Spacing.stackMd,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Palette.outlineVariant,
  },
  prefRowLast: { borderBottomWidth: 0, paddingBottom: 0 },
  prefKey: { ...Typography.bodyMd, color: Palette.onSurface },
  prefValue: { ...Typography.bodyMd, color: Palette.onSurfaceVariant },
  signOutButton: {
    borderWidth: 1,
    borderColor: Palette.error,
    borderRadius: Radius.lg,
    paddingVertical: Spacing.stackMd,
    alignItems: "center",
  },
  signOutButtonPressed: { opacity: 0.7 },
  signOutText: { ...Typography.bodyMd, color: Palette.error },
  errorText: {
    ...Typography.bodyMd,
    color: Palette.error,
    textAlign: "center",
    paddingHorizontal: Spacing.containerMargin,
  },
});
