import { StyleSheet } from "react-native";

import { Palette, Radius, Spacing, Typography } from "@/constants/design";

const actionButton = {
  borderWidth: 1,
  borderRadius: Radius.lg,
  height: 44,
  paddingVertical: 12,
  alignItems: "center" as const,
  justifyContent: "center" as const,
};

const ACTION_GROUP_GAP = Spacing.stackMd;
const ACTION_BUTTON_HEIGHT = 44;

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: Palette.background },
  centered: { flex: 1, alignItems: "center", justifyContent: "center" },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 48,
    paddingVertical: Spacing.stackMd,
    paddingHorizontal: Spacing.containerMargin,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Palette.outlineVariant,
  },
  wordmark: {
    ...Typography.labelSm,
    color: Palette.onSurface,
    letterSpacing: 6,
    fontSize: 14,
    lineHeight: 20,
  },
  profileActions: {
    position: "relative",
    height: ACTION_BUTTON_HEIGHT * 2 + ACTION_GROUP_GAP,
  },
  actionGroup: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    gap: ACTION_GROUP_GAP,
  },
  editProfileButton: {
    ...actionButton,
    borderColor: Palette.primary,
  },
  buttonPressed: { opacity: 0.7 },
  editProfileButtonText: { ...Typography.labelSm, color: Palette.primary },
  cancelButton: {
    ...actionButton,
    borderColor: Palette.outlineVariant,
  },
  cancelButtonText: { ...Typography.labelSm, color: Palette.onSurfaceVariant },
  saveButton: {
    ...actionButton,
    backgroundColor: Palette.primary,
    borderColor: Palette.primary,
  },
  saveButtonDisabled: { opacity: 0.6 },
  saveButtonInner: {
    height: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  saveButtonText: { ...Typography.labelSm, color: Palette.onPrimary },
  scrollView: { flex: 1 },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: Spacing.containerMargin,
    paddingTop: Spacing.stackLg,
    paddingBottom: Spacing.stackXl,
    gap: Spacing.stackLg,
  },
  profileHeader: {
    alignItems: "center",
    gap: Spacing.stackSm,
    paddingTop: Spacing.stackSm,
  },
  avatar: {
    width: 96,
    height: 96,
    borderRadius: Radius.full,
    backgroundColor: Palette.surfaceContainerHigh,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: Spacing.stackSm,
  },
  avatarInitials: {
    ...Typography.headlineMd,
    color: Palette.onSurface,
    lineHeight: 36,
    transform: [{ translateY: 3 }],
  },
  nameSlot: {
    height: 36,
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
  },
  nameField: {
    width: "100%",
    height: 34,
    position: "relative",
  },
  nameUnderlineWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: "center",
  },
  nameUnderline: {
    width: 200,
    height: 1,
    backgroundColor: Palette.primary,
  },
  nameInput: {
    width: "100%",
    height: 34,
    lineHeight: 34,
    color: Palette.onSurface,
    padding: 0,
    margin: 0,
    textAlign: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
  },
  email: { ...Typography.bodyMd, color: Palette.onSurfaceVariant },
  bentoGrid: { gap: Spacing.gutter },
  bentoRow: { flexDirection: "row", alignItems: "stretch", gap: Spacing.gutter },
  card: {
    backgroundColor: Palette.surfaceContainer,
    borderRadius: Radius.lg,
    padding: Spacing.stackLg,
  },
  cardHalf: { flex: 1 },
  cardLabel: {
    ...Typography.labelSm,
    color: Palette.onSurfaceVariant,
    marginBottom: Spacing.stackSm,
  },
  cardField: {
    height: 40,
    justifyContent: "center",
    alignItems: "flex-start",
  },
  genderField: {
    justifyContent: "flex-end",
    paddingBottom: 2,
  },
  cardValue: { color: Palette.onSurface },
  heightRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    height: 28,
  },
  inputWrap: {
    height: 28,
    position: "relative",
  },
  ageWrap: {
    width: 40,
  },
  feetWrap: { width: 24 },
  inchesWrap: { width: 36 },
  fieldInput: {
    width: "100%",
    height: 28,
    lineHeight: 28,
    color: Palette.onSurface,
    padding: 0,
    margin: 0,
    textAlign: "left",
    backgroundColor: "transparent",
    borderWidth: 0,
  },
  inputUnderline: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 1,
    backgroundColor: Palette.primary,
  },
  heightSep: { color: Palette.onSurface },
  friendsButton: {
    ...actionButton,
    borderColor: Palette.outlineVariant,
    flexDirection: "row",
    justifyContent: "center",
    gap: Spacing.stackSm,
  },
  friendsButtonText: { ...Typography.labelSm, color: Palette.onSurface },
  signOutButton: {
    ...actionButton,
    borderColor: Palette.error,
  },
  signOutText: { ...Typography.labelSm, color: Palette.error },
  errorText: {
    ...Typography.bodyMd,
    color: Palette.error,
    textAlign: "center",
    paddingHorizontal: Spacing.containerMargin,
  },
});
